dtc_codes = {
    11: "Crankshaft Position Circuit",
    12: "MAF Circuit",
    13: "Engine Temp Circuit ",
    14: "VSS Circuit",
    21: "Ignition Signal Circuit",
    31: "ECM",
    32: "EGR Function",
    33: "LH O2 Circuit",
    34: "Knock Sensor Circuit",
    35: "EGR Temp Sensor Circuit",
    42: "Fuel Temp Sensor Circuit",
    43: "TPS Circuit",
    45: "Injector Leak",
    51: "Injector Circuit",
    53: "RH O2 Circuit",
    54: "AT ECU Signal",
    55: "No Faults",
}